name: communication-management

services:
  # External Dependencies
  azurite:
    container_name: azurite
    image: mcr.microsoft.com/azure-storage/azurite
    command: azurite --silent
    network_mode: host
    profiles:
      - test

  azurite-setup:
    container_name: azurite-setup
    build:
      context: ./
      dockerfile: ./dependencies/azurite/Dockerfile
    network_mode: host
    depends_on:
      - azurite
    environment:
      - AZURITE_CONNECTION_STRING=${AZURITE_CONNECTION_STRING}
      - BLOB_CONTAINER_NAME=${BLOB_CONTAINER_NAME}
    profiles:
      - test

  # Functions
  process-pilot-data:
    container_name: process-pilot-data
    network_mode: host
    build:
      context: ./src/functions/process_pilot_data/
      dockerfile: Dockerfile
    environment:
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - ASPNETCORE_URLS=http://*:7071
      - FUNCTIONS_WORKER_RUNTIME=python
      - BLOB_CONTAINER_NAME=${BLOB_CONTAINER_NAME}
      - CONTACT_TELEPHONE_NUMBER=${CONTACT_TELEPHONE_NUMBER}
      - NOTIFY_FUNCTION_URL=${NOTIFY_FUNCTION_URL}

    depends_on:
      - azurite

  notify:
    container_name: notify
    network_mode: host
    build:
      context: ./src/functions/notify/
      dockerfile: Dockerfile
    environment:
      - AzureWebJobsStorage=UseDevelopmentStorage=true
      - ASPNETCORE_URLS=http://*:7072
      - NOTIFY_API_URL=${NOTIFY_API_URL}
      - NOTIFY_API_KEY=${NOTIFY_API_KEY}
      - NOTIFY_API_KID=${NOTIFY_API_KID}
      - OAUTH2_TOKEN_URL=${OAUTH2_TOKEN_URL}
      - PRIVATE_KEY_PATH=${PRIVATE_KEY_PATH}
