"""Add channel statuses

Revision ID: 7a06fb9a2530
Revises: c058c50d5dc6
Create Date: 2025-01-17 10:51:01.422374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a06fb9a2530'
down_revision: Union[str, None] = 'c058c50d5dc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_statuses',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('message_reference', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DELIVERED', 'READ', 'NOTIFICATION_ATTEMPTED', 'UNNOTIFIED', 'REJECTED', 'NOTIFIED', 'RECEIVED', 'PERMANENT_FAILURE', 'TEMPORARY_FAILURE', 'TECHNICAL_FAILURE', name='channelstatus'), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('channel_statuses')
    # ### end Alembic commands ###
