"""Initial migration

Revision ID: b3d29072b5a1
Revises: 
Create Date: 2025-01-17 10:47:29.920569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d29072b5a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_messages',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('message_reference', sa.UUID(), nullable=False),
    sa.Column('nhs_number', sa.Text(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOT_SENT', 'SENT', 'FAILED', name='batchmessagestatus'), nullable=False),
    sa.PrimaryKeyConstraint('batch_id', 'message_reference', 'status')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('batch_messages')
    # ### end Alembic commands ###
