"""Add message statuses

Revision ID: c058c50d5dc6
Revises: b3d29072b5a1
Create Date: 2025-01-17 10:50:39.877207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c058c50d5dc6'
down_revision: Union[str, None] = 'b3d29072b5a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_statuses',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('message_id', sa.String(), nullable=True),
    sa.Column('message_reference', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PENDING_ENRICHMENT', 'ENRICHED', 'SENDING', 'DELIVERED', 'FAILED', name='messagestatus'), nullable=True),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_statuses')
    # ### end Alembic commands ###
